// Generated by CoffeeScript 1.6.3
var api, getUrl, packages, promise, scrape;

promise = require('when');

scrape = require('scrape');

api = 'https://www.nuget.org/profiles/:user';

getUrl = function(user) {
  if (user == null) {
    user = '';
  }
  return api.replace(':user', user);
};

packages = function(user) {
  var deferred, process, request;
  deferred = promise.defer();
  request = function() {
    var url;
    ++requests;
    url = getUrl(user);
    return scrape.request(url, function(err, $) {
      return process(err, $);
    });
  };
  process = function(err, $) {
    var count, stats;
    stats = $('.stat-number');
    count = +stats[1].innerHTML;
    if (err) {
      return deferred.reject(err);
    } else {
      return deferred.resolve(count);
    }
  };
  request();
  return deferred.promise;
};

module.exports = packages;
