// Generated by CoffeeScript 1.6.3
var api, getUrl, packages, promise, scrape;

promise = require('when');

scrape = require('scrape');

api = 'https://www.nuget.org/profiles/:user';

getUrl = function(user) {
  if (user == null) {
    user = '';
  }
  return api.replace(':user', user);
};

packages = function(user) {
  var deferred, process, request;
  deferred = promise.defer();
  request = function() {
    var url;
    url = getUrl(user);
    return scrape.request(url, process);
  };
  process = function(err, $) {
    var stats;
    stats = $('.stat-number');
    if (err) {
      return deferred.reject(err);
    } else if (!stats[0]) {
      return deferred.reject('User does not exist');
    } else {
      return deferred.resolve(+stats[0].children[0].data);
    }
  };
  request();
  return deferred.promise;
};

module.exports = packages;
